---
title: "Title Goes Here"
author: "Names Go Here" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

library(jsonlite)

# For U.S. Census Bureau data
#library(tigris)

# For pretty tables
#library(kableExtra)
library(knitr)

## Functions 

# Function for formatted table output

output_formatted_table = function(table, text){
  
  table %>% 
    kable(caption = text) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T) %>%
    scroll_box(width = "100%")
}


```
## Load and Clean Data

```{r}
# UMD
umd_police_arrest_data <- read_csv("../data/handmade/umd/umd_police_arrest_data_2021-11-28.csv")
umd_police_incident_data <- read_csv("../data/handmade/umd/umd_police_incident_data_2021_09_13.csv")




```

## Clean

```{r}

# Clean UMD
umd_police_arrest_data_clean = umd_police_arrest_data %>% 
  mutate(date = substr(arrested_date_time_charge,1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(arrested_date_time_charge," ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  select(-c(1))

umd_police_incident_data_clean = umd_police_incident_data %>% 
  mutate(date = substr(occured_date_time_location, 1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(occured_date_time_location, " ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) 
  



```
```{r}
# time of day -- for arrest
umd_arrest_time = umd_police_arrest_data %>% 
  mutate(date = substr(arrested_date_time_charge,1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(arrested_date_time_charge," ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  select(-c(1)) %>% 
  mutate(time_list = (str_split(time,":"))) %>% 
  mutate(time_hour = time_list[[1]]) %>% 
  group_by(time_hour) %>% 
  count()

# time of day -- for incident
umd_incident_time = umd_police_incident_data %>% 
  mutate(date = substr(occured_date_time_location, 1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(occured_date_time_location, " ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  select(-c(1)) %>% 
  mutate(time_list = (str_split(time,":"))) %>% 
  mutate(time_hour = time_list[[1]]) %>% 
  group_by(time_hour) %>% 
  count()

```


```{r}


```

```{r}


incident_by_years = umd_police_incident_data_clean %>% 
  group_by(year) %>% 
  filter(year>=2014) %>% 
  summarise(number_incidents = n())

incident_by_years %>%  ggplot(aes(x = year, y = number_incidents))+
  geom_bar(stat = "identity")



```








## Key observations for UMD Page

```{r}

## Number of Arrest cases

# just a line graph
umd_arrest_cases_by_year = umd_police_arrest_data_clean %>% 
  distinct(year, umpd_case_number) %>% 
  group_by(year) %>% 
  summarise(number_arrest_cases = n())

# people by race, can be over all, and then can be by year
umd_people_by_race = umd_police_arrest_data_clean %>% 
  distinct(year, umpd_case_number, arrest_number, race)

## overall
all_people_by_race = umd_people_by_race %>% 
  group_by(race) %>% 
  summarise(num_people = n())

## by year
umd_by_year_race = umd_people_by_race %>% 
  group_by(year, race) %>% 
  summarise(num_people = n())

ggplot(umd_by_year_race, aes(x = year, y = num_people, fill = race))+
  geom_bar(stat = "identity", position = "dodge")

```


## Key Observations for Salisbury Page


```{r}
salisbury_plot_1_data = salisbury_clean %>% 
  group_by(year, case_no) %>% 
  summarise(num_cases = n()) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(num_cases = n())

salisbury_plot_1 = salisbury_plot_1_data %>% 
  ggplot(aes(x = year, y = num_cases)) +
  geom_line()+
  labs(title="Number of Police Cases at Salisbury University")+
  ylab("Number of Cases")+
  xlab("Year")

salisbury_plot_1
```
#Categories Problem

```{r}


unique(umd_police_arrest_data_clean$description)
unique(salisbury_clean$incident_type)


```

