---
title: "Title Goes Here"
author: "Names Go Here" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

# For U.S. Census Bureau data
library(tigris)

# For pretty tables
library(kableExtra)
library(knitr)

## Functions 

# Function for formatted table output

output_formatted_table = function(table, text){
  
  table %>% 
    kable(caption = text) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T) %>%
    scroll_box(width = "100%")
}

files_to_df = function(path, type){
  # path is the string file path
  # type is in the format of "*csv"
  
  merged_data <- do.call(bind_rows, lapply(list.files(pattern = type, path = path), function(i){
  path = paste0(path, i)
  df = read_csv(path)
  
  if (ncol(df) == 7){
    df = df %>% 
    clean_names() %>% 
    separate(x2, c("incident", "incident_narrative"), sep = ":", remove = TRUE)
    
    colnames(df) <- c('x1','x2',"x3", "x4", "x5", "x6", "x7", "x8")
    
    return(df)
  }
  
  else{
    df = df %>% 
    clean_names()
    
    return(df)
    
  }
  
  
  }))
  
  return(merged_data)
}


```
## Load and Clean Data

```{r}


gt_incident_log = files_to_df("../data/handmade/gt/csv3/", "*csv") %>% 
  mutate_all(~gsub('[^ -~]', '', .)) %>% 
  mutate_all(tolower) %>% 
  filter(!(str_detect(x1, "report date"))) %>% 
  filter(!(str_detect(x1, "crime log"))) 

colnames(gt_incident_log) <- c('report_date','incident',"incident_narrative", "incident_number", "date_occured", "time_occured", "general_location", "disposition")

gt_incident_log = gt_incident_log %>% 
 mutate(date_occured = mdy(date_occured)) %>% 
 mutate(year_occured = year(date_occured)) %>% 
 mutate(report_date = mdy(report_date)) %>% 
 mutate(year_reported = year(report_date))
  

```

## Export

```{r}

write_rds(gt_incident_log, "../data/processed/etl_gt_incident_log.rds")
write_csv(gt_incident_log, "../data/processed/etl_gt_incident_log.csv")




```



