---
title: "Title Goes Here"
author: "Names Go Here" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

# For U.S. Census Bureau data
library(tigris)

# For pretty tables
library(kableExtra)
library(knitr)

## Functions 

# Function for formatted table output

output_formatted_table = function(table, text){
  
  table %>% 
    kable(caption = text) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T) %>%
    scroll_box(width = "100%")
}

files_to_df = function(path, type){
  # path is the string file path
  # type is in the format of "*csv"
  
  merged_data <- do.call(rbind, lapply(list.files(pattern = type, path = path), function(file_name){
  path = paste0(path, i)
  df = read_csv(path)}))
  
  return(merged_data)
}



```
## Load and Clean Data

```{r}

test = lapply(list.files(pattern = "*csv", path = "../data/handmade/howard/csvs/"), function(file_name){
  path = paste0("../data/handmade/howard/csvs/", file_name)
  df = read_csv(path)
  df = df %>% 
  clean_names()
  
  print(df)

  ls_columns = colnames(df)
  
  col_one = c("natures_of_crimes", "case_numbers", "date_time_reported", "date_time_occurred", "general_location")
  col_three = c("natures_of_crimes", "case_numbers", "date_time_reported", "date_time_occurred")
  
  
  if(identical(ls_columns, col_one) == TRUE){
    df = df %>% 
      mutate(general_location = tolower(general_location)) %>% 
      mutate(disposition = case_when(
      str_detect(general_location, "inactive") ~ "inactive",
      str_detect(general_location, "active") ~ "active"
      )) %>% 
      mutate(general_location = str_replace(general_location, "inactive", "")) %>% 
      mutate(general_location = str_replace(general_location, "active", "")) %>% 
      mutate(general_location = str_replace(general_location, ",", "")) %>% 
      separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>% 
      separate(date_time_occurred, c("date_occurred", "time_occurred"), sep = " ")
    
  }
  
  if(identical(ls_columns, col_three) == TRUE) {
    if(str_detect(df[1, "date_time_reported"][[1]], "/") == TRUE){
      df = df %>% 
      separate(date_time_reported, c("date_reported", "time_reported"), sep = "/") %>% 
      separate(date_time_occurred, c("date_occurred", "time_location_occurred"), sep = "/") %>% 
      separate(time_location_occurred, c("time_occurred", "general_location"), sep = ",") %>% 
      mutate(disposition = NA)
      
    }
    
  }
  
  if(identical(ls_columns, col_three) == TRUE ){
    if (str_detect(df[1, "date_time_reported"][[1]], "am") == TRUE |str_detect(df[1, "date_time_reported"][[1]], "pm") == TRUE ){
      df = df %>% 
      separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>%
      separate(date_time_occurred, c("date_time_occurred", "general_location"), sep = ",") %>% 
      separate(date_time_occurred, c("date_occured", "time_occurred"), sep = " ") %>% 
      mutate(disposition = NA)
    }
  }
  return(df)
})

howard_incident_log = files_to_df("../data/handmade/howard/csvs/", "*csv")
howard_incident_log  = gw_incident_logs %>% 
  # clean names
  clean_names() 


clean_howard = function(file_name){
  path = paste0(path, file_name)
  df = read_csv(path)
  df = df %>% 
  clean_names()

  ls_columns = colnames(df)
  
  col_one = c("natures_of_crimes", "case_numbers", "date_time_reported", "date_time_occurred", "general_location")
  col_three = c("natures_of_crimes", "case_numbers", "date_time_reported", "date_time_occurred")
  
  
  if(identical(ls_columns, col_one) == TRUE){
    df = df %>% 
      mutate(general_location = tolower(general_location)) %>% 
      mutate(disposition = case_when(
      str_detect(general_location, "inactive") ~ "inactive",
      str_detect(general_location, "active") ~ "active"
      )) %>% 
      mutate(general_location = str_replace(general_location, "inactive", "")) %>% 
      mutate(general_location = str_replace(general_location, "active", "")) %>% 
      mutate(general_location = str_replace(general_location, ",", "")) %>% 
      separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>% 
      separate(date_time_occurred, c("date_occurred", "time_occurred"), sep = " ")
    
  }
  
  if(identical(ls_columns, col_three) == TRUE & str_detect(df[1, "date_time_reported"][[1]], "/") == TRUE){
    df = df %>% 
    separate(date_time_reported, c("date_reported", "time_reported"), sep = "/") %>% 
    separate(date_time_occurred, c("date_occurred", "time_location_occurred"), sep = "/") %>% 
    separate(time_location_occurred, c("time_occurred", "general_location"), sep = ",") %>% 
    mutate(disposition = NA)
  }
  
  if(identical(ls_columns, col_three) == TRUE & (str_detect(df[1, "date_time_reported"][[1]], "am") == TRUE |str_detect(df[1, "date_time_reported"][[1]], "pm") == TRUE )){
    df = df %>% 
    separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>%
    separate(date_time_occurred, c("date_time_occurred", "general_location"), sep = ",") %>% 
    separate(date_time_occurred, c("date_occured", "time_occurred"), sep = " ") %>% 
    mutate(disposition = NA)
  }
  
  return(df)
  
  
}
  

###
identical(colnames(test[[2]]), colnames(test[[3]]))
identical

test1 = test[[2]]  %>% 
  mutate(general_location = tolower(general_location)) %>% 
  mutate(disposition = case_when(
    str_detect(general_location, "inactive") ~ "inactive",
    str_detect(general_location, "active") ~ "active"
  )) %>% 
  mutate(general_location = str_replace(general_location, "inactive", "")) %>% 
  mutate(general_location = str_replace(general_location, "active", "")) %>% 
  mutate(general_location = str_replace(general_location, ",", "")) %>% 
  separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>% 
  separate(date_time_occurred, c("date_occurred", "time_occurred"), sep = " ")



####
identical(colnames(test[[5]]), colnames(test[[6]]))
identical(colnames(test[[6]]), colnames(test[[7]]))

test2 = test[[5]]  %>% 
  separate(date_time_reported, c("date_reported", "time_reported"), sep = "/") %>% 
  separate(date_time_occurred, c("date_occurred", "time_location_occurred"), sep = "/") %>% 
  separate(time_location_occurred, c("time_occurred", "general_location"), sep = ",") %>% 
  mutate(disposition = NA) %>% 
  View()

#### 
identical(colnames(test[[7]]), colnames(test[[8]]))

test3 = test[[7]] %>% 
  separate(date_time_reported, c("date_reported", "time_reported"), sep = " ") %>%
  separate(date_time_occurred, c("date_time_occurred", "general_location"), sep = ",") %>% 
  separate(date_time_occurred, c("date_occured", "time_occurred"), sep = " ") %>% 
  View()
  

### doing it for 2
 




str_replace("wonder plaza lot,inactive", "inactive", " ")

#%>% 
  # make date columns a date type
 # mutate(date_reported = mdy(date_reported),
  #       date_occurred = mdy(date_occurred))
  

```


```{r}

trishas_function = function(x){
  variable = (x*2)
  return(variable)
}

trishas_function(6)
  

```

## Export

```{r}

write_rds(gwu_incident_log, "../data/processed/gwu_incident_log.rds")
write_csv(gwu_incident_log, "../data/processed/gwu_incident_log.csv")




```



