---
title: "Title Goes Here"
author: "Names Go Here" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

# For U.S. Census Bureau data
# library(tigris)

# For pretty tables
library(kableExtra)
library(knitr)
library(jsonlite)





library(bbplot)


if(!require(pacman))install.packages("pacman")

pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')
```


```{r}


create_df_from_json_files = function(directory){
  files = list.files(directory)
  counter = 0
  for (i in files){
    path = paste0(directory, i)
    counter = counter + 1
    if (counter == 1){
      df <- fromJSON(path)
      df = fromJSON(df)
    } else{
      new_df = fromJSON(path)
      new_df = fromJSON(new_df)
      df = bind_rows(df,new_df)
    }
  
  }
  
  df = df %>% 
    clean_names()
  
  return(df)
  
  
}

directory = "../data/handmade/salisbury/jsons_final/"

salisbury = create_df_from_json_files(directory)

```

## Clean Salisbury


```{r}
salisbury_clean = salisbury %>% 
  mutate(incident_type = tolower(str_squish(incident_type))) %>% 
  mutate(report_date = mdy(report_date)) %>% 
  mutate(year = year(report_date)) %>% 
  mutate(extra_column = case_when(
    str_detect(incident_type, "sex") ~ "sex"
  ))
  
salisbury_plot_1_data = salisbury_clean %>% 
  group_by(year, case_no) %>% 
  summarise(num_cases = n()) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(num_cases = n())

salisbury_plot_1 = salisbury_plot_1_data %>% 
  ggplot(aes(x = year, y = num_cases)) +
  geom_line()+
  labs(title="Number of Police Cases at Salisbury University")+
  ylab("Number of Cases")+
  xlab("Year")

salisbury_plot_1

  
```
## Interesting groupings
```{r}


unique(salisbury_clean$incident_type)
```

