---
title: "Title Goes Here"
author: "Names Go Here" 
output:
  html_document:
    theme: cerulean
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
  md_document:
    variant: markdown_github
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



## Load Libraries, Settings and Global Functions
```{r warning=FALSE,error=FALSE,message=FALSE}
# For general data science
library(tidyverse)

# For data cleaning
library(janitor)

# For loading Excel files
library(readxl)

# For working with datetime
library(lubridate)

# For U.S. Census Bureau data
#library(tigris)

# For pretty tables
#library(kableExtra)
library(knitr)

## Functions 

# Function for formatted table output

output_formatted_table = function(table, text){
  
  table %>% 
    kable(caption = text) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 14, fixed_thead = T) %>%
    scroll_box(width = "100%")
}


```
## Load and Clean Data

```{r}

umd_police_arrest_data <- read_csv("~/Code/university_police_logs/data/handmade/umd_police_arrest_data_2021_09_13.csv")

umd_police_incident_data <- read_csv("~/Code/university_police_logs/data/handmade/umd_police_incident_data_2021_09_13.csv")


```

## Clean

```{r}

# Change
umd_police_arrest_data = umd_police_arrest_data %>% 
  mutate(date = substr(arrested_date_time_charge,1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(arrested_date_time_charge," ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) %>% 
  select(-`...1`)
  
umd_police_incident_data = umd_police_incident_data %>% 
  mutate(date = substr(occured_date_time_location, 1,8)) %>% 
  rowwise() %>% 
  mutate(time = strsplit(occured_date_time_location, " ")[[1]][2]) %>% 
  mutate(date = mdy(date)) %>% 
  mutate(year = year(date)) 


```


```{r}

type_crime_by_year = umd_police_arrest_data %>% 
  filter(description == "CDS: Possess Paraphernalia") %>% 
  group_by(year, description) %>% 
  summarise(number_crimes = n())

ggplot(type_crime_by_year, aes(x = year, y = number_crimes))+
  geom_bar(stat = "identity")+
  theme(legend.position = "none")+
    ggtitle("testing")

for (i in c(2010:2021)){
  
  print(year)
  plot = type_crime_by_year %>% 
    filter(year == i) %>% 
  ggplot(aes(x = year, y = number_crimes, fill = description))+
  geom_bar(stat = "identity", position = "dodge")+
  theme(legend.position = "none")+
    ggtitle(paste0("Crime breakdown for: ", year))
  
  print(plot)
  
}

# graph crime by year

# nick
umd, george town

#aadit
howard, georgwashingotn

```

## Exploring
```{r}
umd_police_arrest_data %>% 
  group_by(description) %>% 
  summarise(n()) %>% 
  View()


umd_police_incident_data %>% 
  group_by(umpd_case_number) %>% 
  count() %>% 
  View()

umd_police_arrest_data %>% 
  group_by(umpd_case_number) %>% 
  count() %>% 
  View()

umd_police_arrest_data %>% 
  group_by(year, umpd_case_number) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(umpd_case_number) %>% 
  summarise(num_across_years = n()) %>% 
  View()

umd_police_arrest_data %>% 
  group_by(arrest_number) %>% 
  count() %>% 
  View()
```

In the incident data there are only one of each umpd case number 

In the arrest data, there could be multiple umpd case numbers

## Summarize arrest data

```{r}

umd_police_arrest_summarized = umd_police_arrest_data %>% 
  group_by(umpd_case_number) %>% 
  mutate(number_people_arrests_or_citations = length(unique(arrest_number))) %>% 
  mutate(number_case_occurences = n())
  
  
race_total_by_case = umd_police_arrest_summarized %>% 
  group_by(year, umpd_case_number, arrest_number) %>% 
  summarise(races = unique(race)) %>% 
  ungroup() %>% 
  group_by(year,umpd_case_number, races) %>% 
  summarise(num = n()) %>% 
  pivot_wider(names_from = races, values_from = num, values_fill = 0) 


description_total_by_case = umd_police_arrest_summarized %>% 
  group_by(year, umpd_case_number) %>% 
  summarise(races = list(description)) %>% 
  ungroup() %>% 
  group_by(year,umpd_case_number) %>% 
  summarise(num = n()) %>% 
  pivot_wider(names_from = races, values_from = num, values_fill = 0) 
```




## Combine

```{r}

umd_police <- left_join(umd_police_incident_data, umd_police_arrest_data, by = "umpd_case_number")


```


## Write out Data
```{r}
write_rds(umd_police_arrest_data, "../data/processed/etl_umd_police_arrest_data.rds")
write_rds(umd_police_incident_data, "../data/processed/etl_umd_police_incident_data.rds")
```

```{r}

etl_umd_police_arrest_data = umd_police_arrest_data


```


